project:
  type: website

website:
  title: "Michael Luu, MPH"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/mluu921
      - icon: linkedin
        href: https://www.linkedin.com/in/miluu/

format:
  html:
    theme: litera
    css: styles.css

editor: visual

