project:
  type: website

website:
  title: "Michael Luu, MPH"
  navbar:
    right:
      - blog.qmd
      - projects.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/mluu921

format:
  html:
    theme: litera
    css: styles.css

editor: visual
